### ISSUE TITLE
Weird power in compute_coupled_cell

### ISSUE THREAD

**Issue by paganol** [LSSTDESC/NaMaster#189] opened 2024-04-14 17:02 UTC
Hi @damonge, I'm getting weird results using `nmt.compute_coupled_cell`. The power in the power spectrum increases a lot with the number of iterations. 

For example, this is what I get for a temperature map with a galactic mask (but I have the same issue with no mask)
![Unknown](https://github.com/LSSTDESC/NaMaster/assets/5398538/b21873e1-4288-4905-ade3-57f6e4fe51d0)
The gray line shows the same computation done with `hp.map2alm`, all the curves are almost overlapped.

Here I plot only `hp.map2alm` result
![Unknown1](https://github.com/LSSTDESC/NaMaster/assets/5398538/5722863b-02f0-4025-8fea-6c1492c5c493)

I've also implemented my own version of `map2alm` with iterations I get exactly the result  of `hp.map2alm`. 

I checked the implementation here 
https://github.com/LSSTDESC/NaMaster/blob/b45317f840320855b7e38799fa411782e2886289/src/healpix_extra.c#L843-L881
but it seems correct

For reference (the issue might be here) I'm using v1.6 with python 3.9 and the conda-forge installation on a M3 machine. 
`namaster                  1.6              py39hfd079a7_5    conda-forge`

Any idea?

**Comment by damonge** [comment] 2024-04-16 07:11
Hi @paganol . That is indeed strange, and I have not seen this in the past. Can you send over the input C_ell you use for this?

**Comment by paganol** [comment] 2024-04-16 13:59
Hi @damonge, I put here a [tar](https://github.com/LSSTDESC/NaMaster/files/14997860/test_iterations_namaster.tgz) with code and inputs.

**Comment by damonge** [comment] 2024-06-13 19:45
@paganol many apologies for the delay. I've tested this now with the latest version of the code, currently on conda, and can't seem to reproduce the issue (see screenshot from the notebook you so kindly provided).

![image](https://github.com/LSSTDESC/NaMaster/assets/8809493/b99685e2-8902-40e7-b4cf-2c3be40e3f67)

This is likely due to the migration to ducc (although I'm also mystified, as I would have expected the implementation on libsharp to be correct).

In any case, I'm hoping this is fixed. I'm closing the issue but please do reopen it if it doesn't appear solved to you, as in that case it may be due to platform differences that I should weed out.

Again thanks for bringing this up.

**Closed by damonge** 2024-06-13 19:45 UTC
