### ISSUE TITLE
negative eigenvalues for weak lensing gaussian covariance

### ISSUE THREAD

**Issue by gouyoub** [LSSTDESC/NaMaster#218] opened 2024-10-08 14:52 UTC
Hello,
I am trying to use pymaster to compute the partial-sky Gaussian covariance matrix of the decoupled bandpowers for 3x2pt. While I have no issue with the covariance of photometric galaxy clustering bandpowers, the one for weak lensing or galaxy-galaxy lensing is not positive definite.

Here is an example code I am using to compute the Gaussian covariance for weak lensing. I am using the latest version of pymaster (v2.2.2)

```
# Loading my theory Cl's and footprint
data_ref = '/home/hidra2/gouyou/euclid/nl_bias_flagship/data/'
ref = '/home/hidra2/gouyou/cosmosis-standard-library/working_dir/output/fs2_nlbias/simulation/fs2_firstchain_linbias_unbinned/'
nzbins = 3
cls_wl, keys_wl = load.get_cosmosis_Cl(ref, nzbins, 'WL', True)
mask = hp.read_map(data_ref+'mask/flagship2_mask_binary_NS512.fits')

# Initializing Nmt objects
nside = 512
fmask = nmt.NmtField(mask, None, spin=0)
b = nmt.NmtBin.from_nside_linear(nside, 20)
w = nmt.NmtWorkspace.from_fields(fmask, fmask, b)
cw = nmt.NmtCovarianceWorkspace.from_fields(fmask, fmask, fmask, fmask)

# Initializing the covariance array
nell = b.get_effective_ells().size
ncl = len(keys_wl)
print(ncl*nell)
covmat = np.zeros((ncl*nell, ncl*nell))

# Assigning symmetric keys to Cl dictionnary
for key in keys_wl:
    probeA, probeB = key.split('-')
    cls_wl['-'.join([probeB, probeA])] = cls_wl[key]

# Computation of all the blocks of the covariance matrix
for (idx1, key1), (idx2, key2) in itertools.combinations_with_replacement(enumerate(keys_wl), 2):
    print(key1, key2, flush=True)
    probeA, probeB = key1.split('-')
    probeC, probeD = key2.split('-')

    covmat[idx1*nell:(idx1+1)*nell, idx2*nell:(idx2+1)*nell] =\
        nmt.gaussian_covariance(cw, 0, 0, 0, 0,
                                [cls_wl['-'.join([probeA, probeC])]],
                                [cls_wl['-'.join([probeB, probeC])]],
                                [cls_wl['-'.join([probeA, probeD])]],
                                [cls_wl['-'.join([probeB, probeD])]],
                                w, wb=w)

covmat = covmat + covmat.T - np.diag(covmat.diagonal())
```

All the individual blocks of the covariance (corresponding to a given pair of Cl's) are positive definite but when considering the entire matrix it is not. To test this I use `np.linalg.cholesky(covmat)`.

Note that I am only computing the E-mode covariance and considering it is a spin-0 field. I also tried with spin-2 fields with a zero contribution from B-modes and the result is the same.

Have you ever encountered this issue ?

I made many tests (varying probes, mask, resolution, binning, lmin, lmax and more) so I can give more details if needed.

Thank you in advance !

Sylvain GB.

**Comment by damonge** [comment] 2024-10-29 15:18
Apologies for the delay. I can see this happening due to numerical errors if the different maps for whose  power spectra you are computing the covariance are very correlated with one another. If that is the case, I would suggest using a PCA approach to compute the inverse covariance (assuming that the number of eigenvalues is relatively small). I'm afraid I can't comment more without a completely reproducible example.

**Comment by gouyoub** [comment] 2024-10-30 09:13
Thank you for your answer !

Indeed, doing some tests I understood that it depends on the level of correlations between the maps. By creating fake n(z) with highly overlapping Gaussians, the covariance was not positive definite, while it is positive definite when the Gaussians have a smaller overlap. So I am guessing that this is what's happening for WL where all the bins are strongly correlated due to shape of the kernels, going from $z=0$ to a given $z$. I'll prepare a reproducible example and plots to illustrate that.

In the meantime I am not sure I understand your suggestion. You are suggesting to invert the matrix in the PCA basis ? The thing is that I am able to invert it (with `np.linalg.inv(cov)` for example). But I am not very confident in using a precision matrix coming from a non-positive definite covariance matrix

**Comment by damonge** [comment] 2024-10-30 10:01
Yes, indeed that can be dangerous, since you'll have negative chi2 directions that can easily derail an MCMC. A PCA approach is usually more stable. Essentially you diagonalise your covariance, look at the eigenvalues, invert those eigenvalues that are positive (or above a given threshold), and then set the rest to zero in the inverse (effectively giving them a large variance). A probably better description here: https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse#Normal_matrices

Since this doesn't seem to be related to NaMaster, I'll close the issue, but let me know if anything else crops up.

**Closed by damonge** 2024-10-30 10:01 UTC

**Comment by gouyoub** [comment] 2024-10-30 15:57
Ok, thank you for the clarification.

However, the initial issue was related to NaMaster producing non-positive definite covariance matrix for highly correlated maps. I would prefer understanding why that is. Maybe I am not using the code in the right way...

I prepared a reproducible example demonstrating the issue. For 2 different fake n(z)'s, one with low overlap and another one with higher overlap between bins, there are 2 different sets of angular power spectra. For a given mask, the partial-sky gaussian covariance matrix is computed in both cases. And the eigenvalues are plotted at the end.

I attache a .gz file containing a notebook and all the necessary files to run it. Tell me if you have any idea about what is going on.

Thank you.
Sylvain.

[nmt_example_gouyoub.tar.gz](https://github.com/user-attachments/files/17575696/nmt_example_gouyoub.tar.gz)

**Comment by damonge** [comment] 2024-10-30 16:29
I think this is not entirely surprising. The way namaster calculates covariances involves an approximation (the Narrow Kernel Approximation). With this, there is no mathematical guarantee that the cross-covariances will be strictly positive-definite. In practice, they are almost always positive-definite indeed, but if you apply this to a case in which the fields involved are very highly correlated with one another (so that some of the eigenvalues of the true covariance are close to zero), it is not surprising that the NKA could lead to a covariance in which these small eigenvalues are pushed to zero or even small negative numbers.

In pathological cases like this I think PCA offers a safe way to regularise the covariance.
